# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build -o ~/.local/bin/gocal
  run:
    cmds:
      - gocal
  default:
    cmds:
      - task build
      - task run
    silent: true
